### ISSUE TITLE
On-board Heanh Sok

### ISSUE THREAD

**Issue by samarth9008** [kaizen-ai/kaizenflow#1023]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/kaizen-ai/kaizenflow/blob/master/README.md.old) 
  - [x] **Read [How to organize your work](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/work_organization/kaizenflow.organize_your_work.how_to_guide.md)**
  - [x] **Read [Quick start for developing](https://github.com/kaizen-ai/kaizenflow/blob/master/docs/onboarding/kaizenflow.set_up_development_environment.how_to_guide.md)**
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md) works and read about our docker methodology
  - [x] **Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) run successfully** 
     - OK if some are failing while running it
  - [x] **Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)**
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [x] Get assigned a warm-up issue
  - [x] **Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)**
  - [x] **How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)**
  - [x]  If you are graduating soon and you would like to get a full-time job in
  one of the companies in the KaizenFlow ecosystem reach out to GP at
  gp@kaizen-tech.io

The one in bold are really imp. Make sure to internalize them

FYI @sonaalKant  @gpsaggese

**Comment by heanhsok** [comment]
Hi @samarth9008 

I'm getting the following error when running unit tests. do I need to setup AWS credential?
```
user_501@728f0331f1e2:/app$ pytest
=============================================================================== test session starts ================================================================================
platform linux -- Python 3.9.5, pytest-7.4.2, pluggy-1.3.0 -- /venv/bin/python
cachedir: .pytest_cache
rootdir: /app
configfile: pytest.ini
plugins: xdist-3.3.1, timeout-2.1.0, instafail-0.5.0, rerunfailures-12.0, cov-4.1.0, anyio-4.0.0
collecting 3067 items                                                                                                                                                              # Git
  branch_name='onboard'
  hash='a0c8bdbe6'
  # Last commits:
    * a0c8bdbe6 Krishna P Taduri SorrTask1018_clean_up_notebooks (#1019)                           (  28 hours ago) Mon Jun 3 13:29:04 2024  (HEAD -> onboard, origin/master, origin/HEAD, master)
    * edb1f430d Nitesh703 Unit test compute_bar_start_timestamps() (#1013)                  (    4 days ago) Fri May 31 14:24:51 2024
    * 1fd89f5a2 GP Saggese Update papers                                                     (    6 days ago) Wed May 29 23:23:33 2024
# Machine info
  system=Linux
  node name=728f0331f1e2
  release=6.6.12-linuxkit
  version=#1 SMP Fri Jan 19 08:53:17 UTC 2024
  machine=aarch64
  processor=aarch64
  cpu count=8
  cpu freq=None
  memory=svmem(total=8326987776, available=7229288448, percent=13.2, used=918134784, free=6571446272, active=1336729600, inactive=195645440, buffers=38580224, cached=798826496, shared=1302528, slab=99848192)
  disk usage=sdiskusage(total=62671097856, used=22773477376, free=36680904704, percent=38.3)
# Packages
  python: 3.9.5
  cvxopt: 1.3.2
  cvxpy: 1.4.2
  gluonnlp: ?
  gluonts: ?
  joblib: 1.3.2
  mxnet: ?
  numpy: 1.26.0
  pandas: 2.1.1
  pyarrow: 15.0.0
  scipy: 1.11.3
  seaborn: 0.13.0
  sklearn: 1.3.1
  statsmodels: 0.14.0
13:46:19 - INFO  hdbg.py init_logger:1010                               Saving log to file '{'tmp.pytest.log'}'
13:46:19 - INFO  hdbg.py init_logger:1015                               > cmd='/venv/bin/pytest'
collected 3097 items / 1 error

====================================================================================== ERRORS ======================================================================================
_________________________________________________________ ERROR collecting research_amp/soccer_prediction/paired_t_test.py _________________________________________________________
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/venv/lib/python3.9/site-packages/_pytest/runner.py", line 372, in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/venv/lib/python3.9/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/venv/lib/python3.9/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/venv/lib/python3.9/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/venv/lib/python3.9/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/venv/lib/python3.9/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/venv/lib/python3.9/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/venv/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/app/research_amp/soccer_prediction/paired_t_test.py", line 32, in <module>
    s3 = haws.get_service_resource(aws_profile="ck", service_name="s3")
  File "/app/helpers/haws.py", line 76, in get_service_resource
    session = get_session(aws_profile)
  File "/app/helpers/haws.py", line 44, in get_session
    credentials = hs3.get_aws_credentials(aws_profile=aws_profile)
  File "/app/helpers/hs3.py", line 723, in get_aws_credentials
    config = _get_aws_config(file_name)
  File "/app/helpers/hs3.py", line 520, in _get_aws_config
    hdbg.dassert_file_exists(file_name)
  File "/app/helpers/hdbg.py", line 785, in dassert_file_exists
    _dfatal(txt, msg, *args, only_warning=only_warning)
  File "/app/helpers/hdbg.py", line 142, in _dfatal
    dfatal(dfatal_txt)
  File "/app/helpers/hdbg.py", line 71, in dfatal
    raise assertion_type(ret)
AssertionError:
################################################################################
* Failed assertion *
File '/home/.aws/credentials' doesn't exist
################################################################################

============================================================================= short test summary info ==============================================================================
ERROR research_amp/soccer_prediction/paired_t_test.py - AssertionError:
################################################################################
* Failed assertion *
File '/home/.aws/credentials' doesn't exist
################################################################################
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================ 1 error in 15.83s =================================================================================
13:46:19 - INFO  hcache.py clear_global_cache:294                       Before clear_global_cache: 'global mem' cache: path='/mnt/tmpfs/tmp.cache.mem', size=64.0 KB
13:46:19 - WARN  hcache.py clear_global_cache:295                       Resetting 'global mem' cache '/mnt/tmpfs/tmp.cache.mem'
13:46:19 - WARN  hcache.py clear_global_cache:305                       Destroying '/mnt/tmpfs/tmp.cache.mem' ...
13:46:19 - INFO  hcache.py clear_global_cache:321                       After clear_global_cache: 'global mem' cache: path='/mnt/tmpfs/tmp.cache.mem', size=nan
```

**Comment by samarth9008** [comment]
No need for setting up credentials

**Comment by heanhsok** [comment]
@samarth9008 could you pls assign me a warm-up issue as well?

**Comment by samarth9008** [comment]
As to https://github.com/kaizen-ai/kaizenflow/issues/1023#issuecomment-2150995169

Could you pls create a PR with a fix? Its easy to review that way

**Comment by heanhsok** [comment]
> As to [#1023 (comment)](https://github.com/kaizen-ai/kaizenflow/issues/1023#issuecomment-2150995169)
> 
> Could you pls create a PR with a fix? Its easy to review that way

Yes I have raised a PR for that. 
https://github.com/kaizen-ai/kaizenflow/pull/1030

**Comment by gpsaggese** [comment]
> I'm also wondering if there are any docs explaining the directory structures, how all the different modules work, and how to run each of them.

There is docs/all.software_components.reference.md and docs/all.code_organization.reference.md but we move too fast and so they are all out of sync.
In any case don't worry about the big picture yet. Let's do things bottom-up.

**Comment by heanhsok** [comment]
Hi @samarth9008 do you have any open issue I can work on?

**Comment by samarth9008** [comment]
We are working on filing some issues.

**Comment by samarth9008** [comment]
Closing as done
