### ISSUE TITLE
Remove global var _NEXT_ORDER_SIDE_PER_ASSET

### ISSUE THREAD

**Issue by sonaalKant** [kaizen-ai/kaizenflow#770]
Ref. : https://github.com/cryptokaizen/cmamp/issues/7601

We want to refactor to remove usage of global variable from https://github.com/sorrentum/sorrentum/blob/master/oms/broker/ccxt/scripts/run_ccxt_broker.py

FYI @jsmerix

**Comment by gpsaggese** [comment]
@sonaalKant the link is on cmamp. Are we onboarding @Vedanshu7 on the other side? If not, we need to copy/paste the issue to Sorrentum

**Comment by Vedanshu7** [comment]
@sonaalKant Ref. : https://github.com/cryptokaizen/cmamp/issues/7601
I am not able to access this link, Can you give me access to open it or paste the issue here?

**Comment by samarth9008** [comment]
No need to access that link. Required info is given over here

**Comment by Vedanshu7** [comment]
@samarth9008 , @sonaalKant I am getting this error while running the test case for this file: https://github.com/sorrentum/sorrentum/blob/master/oms/broker/ccxt/scripts/run_ccxt_broker.py

Error:

```

================================================================================================= FAILURES =================================================================================================
_________________________________________________________________________________________ TestRunCcxtBroker1.test1 _________________________________________________________________________________________
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/app/oms/broker/ccxt/scripts/test/test_run_ccxt_broker.py", line 64, in test1
    obcsrccbr._main(mock_argument_parser)
  File "/app/oms/broker/ccxt/scripts/run_ccxt_broker.py", line 550, in _main
    broker = obccbrin.get_CcxtBroker(
  File "/app/oms/broker/ccxt/ccxt_broker_instances.py", line 321, in get_CcxtBroker
    ccxt_broker = get_CcxtBroker_prod_instance1(
  File "/app/oms/broker/ccxt/ccxt_broker_instances.py", line 135, in get_CcxtBroker_prod_instance1
    sync_exchange, async_exchange = obccccut.create_ccxt_exchanges(
  File "/app/oms/broker/ccxt/ccxt_utils.py", line 269, in create_ccxt_exchanges
    exchange_params = hsecret.get_secret(secrets_id)
  File "/app/helpers/hsecrets.py", line 45, in get_secret
    client = get_secrets_client(aws_profile)
  File "/app/helpers/hsecrets.py", line 21, in get_secrets_client
    session = haws.get_session(aws_profile)
  File "/app/helpers/haws.py", line 44, in get_session
    credentials = hs3.get_aws_credentials(aws_profile=aws_profile)
  File "/app/helpers/hs3.py", line 723, in get_aws_credentials
    config = _get_aws_config(file_name)
  File "/app/helpers/hs3.py", line 520, in _get_aws_config
    hdbg.dassert_file_exists(file_name)
  File "/app/helpers/hdbg.py", line 785, in dassert_file_exists
    _dfatal(txt, msg, *args, only_warning=only_warning)
  File "/app/helpers/hdbg.py", line 142, in _dfatal
    dfatal(dfatal_txt)
  File "/app/helpers/hdbg.py", line 71, in dfatal
    raise assertion_type(ret)
AssertionError: 
################################################################################
* Failed assertion *
File '/home/.aws/credentials' doesn't exist
################################################################################


```

Can you please guide me about the same?

**Comment by sonaalKant** [comment]
You don't have access, lets pause this until you are onboarded on cmamp. Meanwhile I will assign you some other task.

**Comment by Vedanshu7** [comment]
Closing this issue as it is completed.
